apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: cfme-external-service
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: cfme-service
  spec:
    ports:
    - name: cfme-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: null
    labels:
      service: cfme
    name: cfme-service
  subsets:
  - addresses:
    - ip: 192.168.0.10
    ports:
    - name: cfme-tcp
      port: 443
      protocol: TCP
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: cfme-route
  spec:
    host: cfme.apps.eformat.nz
    tls:
      termination: passthrough
    to:
      kind: Service
      name: cfme-service
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2016-08-30T02:06:22Z
        status: "True"
        type: Admitted
      host: cfme.apps.eformat.nz
      routerName: router
